[project]
name = "heart-of-gold-button"
version = "0.1.0"
description = "Simple App showing hx-get behavior from HTMX"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "python-fasthtml>=0.6.10",
]
